
package system_final;

import java.awt.Component;
import java.awt.HeadlessException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author WINDOWS 10
 */
public class Signup_seeker extends javax.swing.JFrame {

    public Signup_seeker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        SignUp_label = new javax.swing.JLabel();
        PNumber_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        ReEnter_label = new javax.swing.JLabel();
        Signup_btn = new javax.swing.JButton();
        PNumber = new javax.swing.JTextField();
        Back_btn = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        Re_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Fname_label = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        Gender_label = new javax.swing.JLabel();
        Email_Address_label = new javax.swing.JLabel();
        Email_Address = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        Lname_label = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        Bday_label = new javax.swing.JLabel();
        addresslb = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        showpassBT = new javax.swing.JCheckBox();
        showpassBT1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Job_Finder_Logo-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Logo)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Logo)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        SignUp_label.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        SignUp_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignUp_label.setText("SIGN UP");

        PNumber_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        PNumber_label.setText("MOBILE NUMBER");

        Password_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Password_label.setText("PASSWORD");

        ReEnter_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ReEnter_label.setText("RE-ENTER PASSWORD");

        Signup_btn.setBackground(new java.awt.Color(0, 0, 0));
        Signup_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Signup_btn.setForeground(new java.awt.Color(255, 255, 255));
        Signup_btn.setText("Sign up");
        Signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signup_btnActionPerformed(evt);
            }
        });

        Back_btn.setBackground(new java.awt.Color(0, 0, 0));
        Back_btn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Back_btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_btn.setText("Login");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("I already have an Account");

        Fname_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Fname_label.setText("FIRST NAME");

        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });

        Gender_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Gender_label.setText("GENDER");

        Email_Address_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Email_Address_label.setText("EMAIL ADDRESS");

        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });

        Lname_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Lname_label.setText("LAST NAME");

        gender.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        month.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        year.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950" }));

        day.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Bday_label.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Bday_label.setText("BIRTHDAY");

        addresslb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addresslb.setText("ADDRESS");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        showpassBT.setText("Show ");
        showpassBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassBTActionPerformed(evt);
            }
        });

        showpassBT1.setText("Show ");
        showpassBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassBT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(SignUp_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Email_Address_label)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(Email_Address))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PNumber_label)
                                            .addComponent(PNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(address)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ReEnter_label)
                                            .addComponent(Gender_label)
                                            .addComponent(Password_label)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(addresslb))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Re_password, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Password))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(showpassBT)
                                            .addComponent(showpassBT1))))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Fname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bday_label)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Signup_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(SignUp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname_label)
                    .addComponent(Lname_label))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gender_label)
                    .addComponent(Bday_label))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_Address_label)
                    .addComponent(PNumber_label))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addresslb)
                .addGap(3, 3, 3)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password_label)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showpassBT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReEnter_label)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Re_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showpassBT1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Back_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signup_btnActionPerformed
         String Fname, Lname, Gender, Month, Day, Year, Email, Pnumber, Address, password, Rpassword, query, emailCheckQuery, phoneCheckQuery;
        String SUrl, SUser, Spass;
        SUrl = "jdbc:MySQL://localhost:3306/job_finder_database";
        SUser = "root";
        Spass = "";

        // Input validation
        if ("".equals(FName.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "First Name is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(LName.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Last Name is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(Email_Address.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Email Address is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(PNumber.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Phone Number is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(address.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Address is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(Password.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Password is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if ("".equals(Re_password.getText())) {
            JOptionPane.showMessageDialog(new JFrame(), "Re-enter Password is Required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 

        Fname = FName.getText();
        Lname = LName.getText();
        Gender = gender.getSelectedItem().toString();
        Month = month.getSelectedItem().toString();
        Day = day.getSelectedItem().toString();
        Year = year.getSelectedItem().toString();
        Email = Email_Address.getText();
        Pnumber = PNumber.getText();
        Address = address.getText();
        password = Password.getText();
        Rpassword = Re_password.getText();

        try (Connection con = DriverManager.getConnection(SUrl, SUser, Spass);
             Statement st = con.createStatement()) {

            // Check if the email already exists in the seeker table
            emailCheckQuery = "SELECT * FROM user_seeker WHERE email = '" + Email + "'";
            ResultSet rsEmail = st.executeQuery(emailCheckQuery);

            if (rsEmail.next()) {
                // Email already exists
                JOptionPane.showMessageDialog(new JFrame(), "Email is already in use. Please use a different email.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if the phone number already exists in the seeker table
            phoneCheckQuery = "SELECT * FROM user_seeker WHERE pnumber = '" + Pnumber + "'";
            ResultSet rsPhone = st.executeQuery(phoneCheckQuery);

            if (rsPhone.next()) {
                // Phone number already exists
                JOptionPane.showMessageDialog(new JFrame(), "Phone Number is already in use. Please use a different phone number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if the passwords match
            if (!password.equals(Rpassword)) {
                JOptionPane.showMessageDialog(new JFrame(), "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Proceed with inserting the new user
            query = "INSERT INTO user_seeker(first_name, last_name, gender, month, day, year, email, Pnumber, address, password) " +
                    "VALUES('" + Fname + "', '" + Lname + "', '" + Gender + "', '" + Month + "', '" + Day + "', '" + Year + "', '" + Email + "', '" + Pnumber + "', '" + Address + "', '" + password + "')";
            st.executeUpdate(query);

            // Show success message
            JOptionPane.showMessageDialog(new JFrame(), "Signup successful! Please log in.", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear input fields
            FName.setText("");
            LName.setText("");
            Email_Address.setText("");
            PNumber.setText("");
            address.setText("");
            Password.setText("");
            Re_password.setText("");

            // Navigate to login screen
            Login_Final LoginFrame = new Login_Final();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(new JFrame(), "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_Signup_btnActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        Login_Final LoginFrame = new Login_Final();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Back_btnActionPerformed

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void showpassBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassBTActionPerformed
        // TODO add your handling code here:
        if (showpassBT.isSelected()) {
            Password.setEchoChar((char) 0); // Make the password visible
        } else {
            Password.setEchoChar('•'); // Hide the password
        }
    }//GEN-LAST:event_showpassBTActionPerformed

    private void showpassBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassBT1ActionPerformed
        // TODO add your handling code here:
        if (showpassBT1.isSelected()) {
            Re_password.setEchoChar((char) 0); // Make the password visible
        } else {
            Re_password.setEchoChar('•'); // Hide the password
        }
    }//GEN-LAST:event_showpassBT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup_seeker().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JLabel Bday_label;
    private javax.swing.JTextField Email_Address;
    private javax.swing.JLabel Email_Address_label;
    private javax.swing.JTextField FName;
    private javax.swing.JLabel Fname_label;
    private javax.swing.JLabel Gender_label;
    private javax.swing.JTextField LName;
    private javax.swing.JLabel Lname_label;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField PNumber;
    private javax.swing.JLabel PNumber_label;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Password_label;
    private javax.swing.JLabel ReEnter_label;
    private javax.swing.JPasswordField Re_password;
    private javax.swing.JLabel SignUp_label;
    private javax.swing.JButton Signup_btn;
    private javax.swing.JTextField address;
    private javax.swing.JLabel addresslb;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JCheckBox showpassBT;
    private javax.swing.JCheckBox showpassBT1;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

    
}
